
import './globals.css'
import Navbar from './componnet/nav'
import { Poppins } from 'next/font/google'

// Subsets are really important. CHECK BELOW FOR MORE INFO
const poppins = Poppins({ 
  
  weight: '400',
  subsets: ['latin'],
  display: 'swap',

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
